server:
  port: 8080
#自己的
#mybatis配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bz_shop?characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.bjsxt.pojo